//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAWatchdog.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.0.10.1")]
        public string healthCheckPingHost {
            get {
                return ((string)(this["healthCheckPingHost"]));
            }
            set {
                this["healthCheckPingHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uTorrent")]
        public global::System.Collections.Generic.List<System.String> processesToKillOnOutage {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["processesToKillOnOutage"]));
            }
            set {
                this["processesToKillOnOutage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int healthCheckIntervalWhileHealthy {
            get {
                return ((int)(this["healthCheckIntervalWhileHealthy"]));
            }
            set {
                this["healthCheckIntervalWhileHealthy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int healthCheckIntervalWhileUnhealthy {
            get {
                return ((int)(this["healthCheckIntervalWhileUnhealthy"]));
            }
            set {
                this["healthCheckIntervalWhileUnhealthy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int consecutiveDownForOutage {
            get {
                return ((int)(this["consecutiveDownForOutage"]));
            }
            set {
                this["consecutiveDownForOutage"] = value;
            }
        }
    }
}
